### ISSUE TITLE
Move sample listings creation out of contracts migration scripts

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#1113]
There are couple things that are wrong with the way we currently create sample listings:
 - It happens as part of a truffle contracts [migration script](https://github.com/OriginProtocol/origin/blob/master/origin-contracts/migrations/3_create_sample_listings.js). Samples creation as nothing to do with contracts so it should be moved out of migration. My suggestion would be into a separate script in charge of populating test data and that gets called as part of starting origin-js. Perhaps [here](https://github.com/OriginProtocol/origin/blob/master/origin-js/scripts/serve.js).
 - It calls contract code directly rather than using origin-js marketplace.createListing - this has some weird effect when testing with sample listing since some data is not populated correctly. For example one can not make an offer on a sample listing.

**Comment by franckc** [comment]
CC @wanderingstan as a FYI since we were chatting about this a day or so ago.

**Comment by tomlinton** [comment]
Just a few further related things:

- It'd be great if the hashes of the listings were not hardcoded (i.e. listing uploaded to IPFS, and returned hash is then used)
- It'd also be great if there were an option to use an external IPFS store rather than the one that gets created by [serve.js](https://github.com/OriginProtocol/origin/blob/master/origin-js/scripts/serve.js), perhaps configurable via environment variables. This might be a separate issue though.

**Comment by nihar97** [comment]
https://github.com/OriginProtocol/origin/pull/1116 attempts to address this issue but breaks becuase of other issues.

**Comment by cuongdo** [comment]
Note that the GraphQL rewrite already has part of this:

https://github.com/OriginProtocol/origin/blob/master/experimental/origin-admin/src/pages/accounts/_populate.js#L187

**Comment by micahalcorn** [comment]
Oops, I'll let someone reopen this, if necessary 🙂
