### ISSUE TITLE
Add a settings page to the DApp

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin#1210]
One of the nice things we get from doing the GraphQL rewrite is that it's easy to switch to fully decentralized mode since all the data is being fetched the same way on the client as it is on the bridge server. We should make it so that users can choose between a slow but censorship-resistant DApp and "performance mode" which is faster but talking to Origin's servers and therefore potentially filtered to comply with US regulations. 

It seems like a good time for us to add a general settings page where we can throw various environment variables that users may want to configure. 

Here are a few settings we'll probably want to include:

**Performance**

 - Fully-decentralized / Mostly-decentralized (Toggle, default to performance mode)

**Search**

 - Search provider (URL, default to Origin's indexing server)

**Trusted providers**

 - Trusted attestation providers (list of ETH addresses, default to ours)
 - Trusted arbitration providers (list of ETH addresses, default to ours)

**Data fetching**

 - IPFS gateway (URL, default to ours)
 - Ethereum gateway (URL, default to Infura)
 - Orbit DB for messaging (address, default to ours)

We don't need to come up with a comprehensive list of settings right now, but it would be good to have a place in the UI where we can start adding configurations & have it wired up to update the universal environment variables for that instance of the DApp. I wanted to mention this as @nick and others work on the rewrite. And for @micahalcorn, @matthewliu and Aure to consider from a product perspective.

**Comment by tomlinton** [comment]
For the implementation the settings should be stored in application state with defaults that are set by environment variables.

The DApp has no concept of an environment like it once did because it is a static JS bundle rather than a process. At build time the environment variables of the environment the DApp is being built in get interpolated into the bundle as strings and they are no longer mutable.

It is also important that they are in application state so that the DApp creator can set them since many of these settings will likely become options in the DApp creator. The DApp creator uses a [base config](https://github.com/OriginProtocol/origin/blob/master/origin-dapp/src/config.js) to populate the defaults which might be a good place for the default settings to live.

**Comment by nick** [comment]
There's already a mockup in Zeplin [here](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5bc779e5e0bf72191e77ec87)

**Comment by tomlinton** [comment]
Done in #1559. It doesn't implement everything considered here but we can add to it as required.
