### ISSUE TITLE
Growth backend updates

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#1376]
Thinks needing to be added / changes on the growth engine backend: 
 - [x] **Domen** campaign model needs a short and a long name ([see these mocks](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c50baae505721bf1338bd41))
- [x] **Franck** an `InviteInformation` graphQl query endpoint should be able to communicate to the invited user who he was invited by. Relates to [this part of Zepplin] (https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c50baa43c692ebf5cd87ad5)
WIP - See #1513 
- [x] **Franck** implement referral rule's reward pending functionality
- [x] **Domen** each rule should have a list of rules that need to be achieved in order for current rule to be unlocked.  [Correlating Zepplin screen](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c50baae505721bf1338bd41) All rules should have an icon and translation text, but we will show only the ones on the frontend that have requiredNextLevel flag
- [x] **Domen** metamask signature and backend authentication
- [x] End date of the campaigns needs to be set at the end of the last day of the month

**Comment by franckc** [comment]
Is the short and long name going to change ? I thought it would be something like:
 - short: "<Month Abreviation> <Year>"
 - long: "<Month> <Year> Campaign"
If so the front-end could create those string programmatically ?

Otherwise the challenge with storing those names in the DB is that those strings need to be translated... I suppose if we do need to go that route, we could store the names in english in the DB and then use that as default for formatted message and then have the formatted message id be the campaign id. Something like:
```
          <FormattedMessage
            id={`Campaign.shortName.${campaign.id}`}
            defaultMessage={`${campaign.shortName}`}
          />
```


Thoughts @sparrowDom ?

**Comment by sparrowDom** [comment]
Yeah good point @franckc, translations do complicate things a bit. Have [asked Matt on Zepplin](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5c50baae505721bf1338bd41
) whether we need support for custom campaign names or not.

**Comment by sparrowDom** [comment]
Updating this issue with decision from Zepplin: we have decided to have a flexible approach where custom short/long names are supported.

**Comment by micahalcorn** [comment]
Are we done here? 😁

**Comment by sparrowDom** [comment]
@franckc can you check the last bullet point? Others are all completed.

**Comment by franckc** [comment]
Done !
Closing this now... :)
