### ISSUE TITLE
Currency Swapping w/DSProxy

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#1838]
This issue tracks the exploration of using [DSProxy](https://github.com/dapphub/ds-proxy) to simplify the user experience associated with converting ETH to DAI, granting the marketplace contract an allowance for moving DAI, and then making an offer on a listing.

**Comment by nick** [comment]
@shahthepro would you be interested in looking at this issue? 

We are aiming to release support for the Dai stablecoin by the end of the week, however the UX for buyers who need to purchase with Dai but don't yet have any involves 3 transactions: Swapping their Eth to Dai via a [Uniswap](https://uniswap.io) exchange contract, approving the Marketplace to move Dai on the user's behalf via the token contract's 'approve' method, then making the offer.

Ideally this could all be done in a single transaction by either leveraging delegatecall, or using [DSProxy](https://github.com/dapphub/ds-proxy). The idea would be to deploy a new proxy contract that allows users to make all 3 calls in a single transaction. We don't want to make any changes to the marketplace contract, and we need msg.sender to be preserved when the user calls makeOffer via the proxy contract... hence the use of delegatecall.

The changes I made to the stablecoin branch today allow you to deploy a local copy of the Uniswap exchange contract via the admin page, then copy the contract addresses to the dapp to use the whole stablecoin UI locally.

Let me know if you're interested in taking a look 😃

**Comment by shahthepro** [comment]
@nick Got it. Will work on it. :)

**Comment by nick** [comment]
Awesome. You may find [this guide](https://github.com/makerdao/developerguides/blob/master/devtools/working-with-dsproxy/working-with-dsproxy.md) helpful for working with DSProxy. Let me know here or on Discord if you need any help getting the stablecoin branch working locally.

**Comment by shahthepro** [comment]
Solidity's [delegatecall](https://solidity.readthedocs.io/en/v0.5.0/introduction-to-smart-contracts.html?highlight=delegatecall#delegatecall-callcode-and-libraries) runs the code in the calling contract's context and not in the called contract's context.

That means the state of the called contract(in our case Uniswap Exchange, Dai Token and Markeplace contracts) cannot be modified by the calling contract(i.e Proxy contract).

DSProxy is [internally uses delegatecall](https://github.com/dapphub/ds-proxy/blob/master/src/proxy.sol#L64) method. So it cannot read/write the called contract's storage either.

We can use `ethToTokenTransferInput()` on Uniswap exchange contract to swap the ETH and transfer it to recipient's address. However, after that, we cannot call `approve()` method within the proxy contract.

---

I can think of one feasible solution. But it requires changing `Marketplace` contract.

We can add a method (say `makeOfferThroughProxy()`) that can be only called by proxy contract (We can restrict access through a modifier).

This method wil be similar to existing `makeOffer()` method but will accept an extra parameter to set the `buyer` address.

1. Use Uniswap exchange contract's `ethToTokenSwapInput()` method. This will exchange the ETH and transfer it back to proxy contract's address.
2. After that we can call the `makeOfferThroughProxy()` method. That will transfer the tokens from Proxy contract to Marketplace contract to make the offer.

Since changing `Marketplace` contract is not being considered at present, I'm not sure if I should go ahead with this approach.

---

I'll probably think of some other ways to see if this is possible without changing contract's code.

**Comment by micahalcorn** [comment]
Moving this to the back burner for now ♨️

**Comment by micahalcorn** [comment]
The current plan is to accomplish a similar goal in conjunction with meta transactions instead of using DSProxy. 🤞
