### ISSUE TITLE
Broken Listing w/Weekend Pricing

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2070]
[One of our featured listings](https://dapp.originprotocol.com/#/listing/1-000-216) is a For Rent housing listing that involves weekend pricing. The price is not being displayed, and the DApp crashes when a buyer tries to select a weekend date.

<img width="1440" alt="Screen Shot 2019-04-18 at 7 56 50 PM" src="https://user-images.githubusercontent.com/273937/56403218-210f5900-6215-11e9-9de6-e899a7dcd707.png">

<img width="1440" alt="Screen Shot 2019-04-18 at 7 56 36 PM" src="https://user-images.githubusercontent.com/273937/56403219-240a4980-6215-11e9-8d1b-88aae92063c5.png">

**Comment by shahthepro** [comment]
Tried debugging it. [This listing's data pinned in IPFS](https://ipfs.originprotocol.com/ipfs/QmaM8FnV2UxAkMqWQpGDkNAV3esbHnTwwBcvoWyHkYo73f) has `listingType` as `unit` instead of `fractional`. However GraphQL query returns `__typename` as `FractionalListing`. 

Was this listing created with a previous version of the DApp?

**Comment by franckc** [comment]
@shahthepro You are right... Looks like listing id 1-000-216 was created back in early January ... So yes it was created on a pretty old version of the DApp, dating prior the graphql rewrite. Personally I don't think it's worth making our code more complex to try to keep backward compatibility for such an old fractional listing since there are so few of them. I would rather keep our code clean. @micahalcorn do you think we could contact the owner of the listing (Luca from Trips) and ask them to update the listing which should cause the data to be written in proper new format ?

**Comment by micahalcorn** [comment]
@lucadgtrip see above. Would you mind updating this one? 🙂

**Comment by lucadgtrip** [comment]
ok we will today thanks!

**Comment by AlessandroTrips** [comment]
Hi guys,

I updated the listing with the weekend prices.

**Comment by nick** [comment]
Seems to be fixed now... please reopen if not
