### ISSUE TITLE
Can't Swipe Back On Android Webview

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2078]
On @kayyoo23's Galaxy S8 and my Nexus 7 (neither having physical buttons), it's apparently not possible to navigate backward in the webview.

**Comment by tomlinton** [comment]
The `allowsBackForwardNavigationGestures` is iOS only because it requires WKWebView. So we have two options:

- Replace `allowsBackForwardNavigationGestures` with a library that detects swipes and we do our own back/forward handling
- Opt for a menu bar arrangement instead with back/forward/refresh buttons. This would also solve #2079 and is clearer than swiping. It would take up screen real estate and probably look ugly, but Aure might have some magic.

It's worth a discussion at least!

**Comment by micahalcorn** [comment]
My preference was to see if we can get away with swiping. Anecdotally, users that I have observed will intuitively try to swipe. That's probably no true for everyone, but I would vote for that path unless implementing swipe navigation for Android is too complex. Assuming that we will eventually move away from the webview, we should encourage users to learn the UX gestures that will be applicable in a fully native app.
