### ISSUE TITLE
Email Verification UX

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2090]
[Our upcoming changes to the onboarding experience for Origin Marketplace (app) involve requiring an email address before anything else](https://zpl.io/bzNOol3). We need to consider whether or not to verify this email address and how this plays into the existing email verification process for the identity attestation. Here are some questions that have been raised:

**Should we block the mobile app UI until the email has been verified?**

 I think not. We'll just have to hope that the link is clicked later. We should also consider delaying the email by a few minutes so as not to distract the user during onboarding. We should also consider where she should land after verifying.

**Should the user be able to click a link in the verification email instead of typing in a numerical code? And, if so, should we change the way this works from the profile page too?**

The link can produce a frustrating experience if the email client opens a different browser than the user was in, especially considering that it isn't likely to be a web3 browser if the email client is on a mobile device. So I think we should keep the numerical code implementation for the profile page. If we're not blocking the experience on the app, then there won't be a natural place to input the code. With that in mind, we should figure out where the user should land after clicking the verification link.

**If an email is verified via app onboarding, should it appear as "verified" when the user first arrives at the profile page?**

It's a bit odd to have to verify the email twice, but the mobile app / email link verification would not have been published to the blockchain. So I don't think we would be able to show it as "verified" in the DApp. At that point, it would only have been verified for our benefit. I guess it's possible that it could be provisionally verified (waiting to be published), but that would require something like a REST API call to check our server for verification status, which seems out of scope. However, this might all change if we are sponsoring gas AND managing keys.

cc @matthewliu

**Comment by joshfraser** [comment]
I think we should continue having people copy a code instead of clicking on a link. The issue you mentioned about clicking on a link and getting taken to the wrong, probably not web3, browser happens all the time and is a really frustrating experience. In addition to the challenges you mentioned, we also have marketplace creator sites that live on different domains as well.

Of course, that means we'll probably want to block the UI to collect the code. Otherwise, I'm not sure how you'd find your way back to the right place.

It's also better if we don't have to question whether an email address was verified or not.

**Comment by matthewliu** [comment]
I'm ok with us sticking with the code and having the code block user activation. It's currently reflected in the newest (still WIP) mocks for 3rd-party mobile wallet, desktop with Metamask, and our future native mobile apps.

https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/dashboard?seid=5cc8d3a287e1dc6863559a3c

https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/dashboard?seid=5cc8c8cdcf972734ba4cedc9

https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/dashboard?seid=5cc32fd9f25db80ffe4801f1

@tomlinton had a question about whether we collect email addresses for mobile native v1.75. not sure if this is the appropriate issue. i am OK with the intermediate weirdness of us collecting the address and the user not having an email attestation (before meta-transactions) since we see this as a short-term state. but if tom feels strongly about not having it in v1.75, i can live without it assuming that we will put it back in once we add meta-transactions and can fast-track that first attestation.

**Comment by tomlinton** [comment]
I'd like to leave it out for a few reasons:

- We aren't using it at the moment
- It is easy to add a prompt to collect it once we have meta transactions
- I think it'll be harder to backfill attestations from email addresses saved previously into the mobile app rather than kicking off an email attestation at the time of collection (and there will be weird edge cases, like people who have an attestation published for a different email address to the one they entered in the mobile app)
- It currently doesn't integrate at all with with the DApp, users will enter the email address in the mobile app and then have to enter it again when performing an attestation

I see no upside, unless there is something I'm missing?

**Comment by matthewliu** [comment]
Ok, let's take it out and then add it in when we have meta-transactions.

**Comment by tomlinton** [comment]
Closed in #2466
