### ISSUE TITLE
Mobile Origin Account Onboarding Components

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2130]
Build the UI components for the new onboarding for Origin Marketplace as shown [here](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9?seid=5c996bf879d02b35ea3596a9). These designs are likely to change with the introduction of Meta Transactions and the "Origin Account" concept.

**Comment by micahalcorn** [comment]
Reducing the scope of this issue and opening the door for someone else to take it on 🙏 (maybe me)

**Comment by tomlinton** [comment]
This is mostly done but I'm uncertain about the email entry. In the mocks the email entry screen only appears when the user clicks "Create a wallet". Is it not necessary when they click "I already have a wallet".

I'm not sure what we want to do with the email once we collect it either. Maybe the original idea here was so that the user could get notifications? I don't think this is necessary any longer with mobile push notifications. I think we should leave the email bit out for now.

**Comment by micahalcorn** [comment]
I think @matthewliu's and @auregimon's preference is to force all users through the email onboarding. If that's the case, then the user would be routed to the email field after entering the phrase. We definitely want them to go through the authentication portion after importing a wallet.

**Comment by matthewliu** [comment]
Yeah, for now we made the decision to grab all emails. In the future we might allow this to be skipped.
