### ISSUE TITLE
[Listener] Indexing failure due to stale contract read

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#2229]
We have an example of a listing that failed indexing on Mainnet due to a stale contract read.
- Listing Id 2731
- Block number 7710150
- Etherscan [link](https://etherscan.io/tx/0xa77a6f8fd777c4c12758e93eabd3734b5c2f22d32458d3811d723ffe32af78e0)

Scenario:
 - Listener gets ListingCreated event
 - getListing is called to get listing data
 - getListing makes a call against a blockchain node to retrieve listing status
 - node is out of sync and returns a failure
 - getListing fails with error "No such listing on contract" - see [code](https://github.com/OriginProtocol/origin/blob/master/packages/eventsource/src/index.js#L83)
 - Listener retries
 - All retries fail, likely because getlisting caches result by listingId, due to the use of lodash's memoize

**Comment by franckc** [comment]
@mikeshultz Another fun bug ! Please double check my reasoning in the scenario above. I have logs, feel free to ping me and I'll send them your way...

**Comment by franckc** [comment]
Now makes me think that having the listener trail by 1 block may have helped with this type of issue in the past...

**Comment by mikeshultz** [comment]
While I do think the scenario you provide is a possibility, that might be helped with an exponential backoff on retries, I don't think that's the problem here.

@franck, can you check if this is happening with *every* `ListingCreated` event?  I suspect it might be and it's related to #2148.  I think the ID with the blockNumber appended to it is being passed to the GraphQL query, which then sends it to event-source, which then pushes it to the contract call.  Should verify, but I think this should be happening with every event if so.

Assuming [I have the right resolver for the query](https://github.com/OriginProtocol/origin/blob/master/packages/graphql/src/resolvers/Marketplace.js#L20-L23) and that [eventsource has no handling of this format of ID](https://github.com/OriginProtocol/origin/blob/master/packages/eventsource/src/index.js#L58-L281), I'd bet this is the cause.

**Comment by mikeshultz** [comment]
Can't be #2148, as it doesn't even touch any of this... where'd this extra blockNumber suffix to the ID come from?

**Comment by mikeshultz** [comment]
I think your scenario is plausible, and perhaps an exponential backoff with retries is warranted here?

```    TypeError: Cannot read property 'id' of null
        at MarketplaceEventHandler._indexListing (/app/infra/discovery/src/listener/handler_marketplace.js:136:39)
        at MarketplaceEventHandler.process (/app/infra/discovery/src/listener/handler_marketplace.js:282:16) 'will retry in 0.24 seconds, retry count 1'```

Might also be good to add a defensive check here and die in a a more useful way while I'm making these changes.

@franckc Can you confirm this is intermittent?  There was only one ListingCreated event in the logs.  And did restarting the listener pick this up just fine?

**Comment by franckc** [comment]
Yes this seems intermittent. Not all events are impacted.

And yes a retries should eventually succeed, though I'm not sure if w want to do the retry within the event-source logic or outside. Might be better outside as to not make the getListing method blocking... But then how to deal with the fact that we cache using memoize the return of getListing ?
Perhaps one idea is that if getListing returns null or an error we shouldn't cache the result.
This way the listener would do the retries and hopefully it would end up succeeding after some time.

**Comment by mikeshultz** [comment]
Mostly a note to myself.  memoize shouldn't be an issue here since this getter call dies in a fire if it's out of bounds on the array of `Listing`s(aka `listings`).  I forced the error to be sure, and web3.js dies with encoding issues:

    @origin/discovery: Error: Couldn't decode address from ABI: 0x
    @origin/discovery:     at SolidityTypeAddress.formatOutputAddress [as _outputFormatter] (/home/mike/dev/origin/node_modules/web3-eth-abi/src/formatters.js:268:15)
    @origin/discovery:     at SolidityTypeAddress.SolidityType.decode (/home/mike/dev/origin/node_modules/web3-eth-abi/src/type.js:252:17)
    @origin/discovery:     at /home/mike/dev/origin/node_modules/web3-eth-abi/src/index.js:327:49
    @origin/discovery:     at Array.forEach (<anonymous>)
    @origin/discovery:     at ABICoder.decodeParameters (/home/mike/dev/origin/node_modules/web3-eth-abi/src/index.js:326:13)
    @origin/discovery:     at Contract._decodeMethodReturn (/home/mike/dev/origin/node_modules/web3-eth-contract/src/index.js:459:22)
    @origin/discovery:     at Method.outputFormatter (/home/mike/dev/origin/node_modules/web3-eth-contract/src/index.js:812:46)
    @origin/discovery:     at Method.formatOutput (/home/mike/dev/origin/node_modules/web3-core-method/src/index.js:163:54)
    @origin/discovery:     at sendTxCallback (/home/mike/dev/origin/node_modules/web3-core-method/src/index.js:475:33)
    @origin/discovery:     at /home/mike/dev/origin/node_modules/web3-core-requestmanager/src/index.js:147:9
    @origin/discovery:     at XMLHttpRequest.request.onreadystatechange (/home/mike/dev/origin/node_modules/web3-providers-http/src/index.js:77:13)
    @origin/discovery:     at XMLHttpRequestEventTarget.dispatchEvent (/home/mike/dev/origin/node_modules/xhr2/lib/xhr2.js:64:18)
    @origin/discovery:     at XMLHttpRequest._setReadyState (/home/mike/dev/origin/node_modules/xhr2/lib/xhr2.js:354:12)
    @origin/discovery:     at XMLHttpRequest._onHttpResponseEnd (/home/mike/dev/origin/node_modules/xhr2/lib/xhr2.js:509:12)
    @origin/discovery:     at IncomingMessage.<anonymous> (/home/mike/dev/origin/node_modules/xhr2/lib/xhr2.js:469:24)
    @origin/discovery:     at IncomingMessage.emit (events.js:198:15)
    @origin/discovery:     at IncomingMessage.EventEmitter.emit (domain.js:481:20)
    @origin/discovery:     at endReadableNT (_stream_readable.js:1139:12)
    @origin/discovery:     at processTicksAndRejections (internal/process/task_queues.js:81:17)

So, on error, there shouldn't be any caching(mild assumption).  I suppose this would be reasonable to implement within `_getListingDetails()` in the marketplace handler if it really is distasteful to implement in eventsource.  Will experiment a bit and get a PR up this afternoon.

**Comment by mikeshultz** [comment]
I have a PR up (#2235) but I kind of hate it.

It's way too specific, for one.  This issue is bound to crop up for any other event handlers with this behavior(say, `OfferCreated`), and should probably be handled at a higher level(say, at handler execution).  And the entire handler should die if any part fails.  And it's basically another layer of this:

    await withRetrys(async () => handleEvent(event, context))

It would be arguably better to just raise `MAX_RETRY_WAIT_MS` or `MAX_RETRYS` instead of merging my PR.  And maybe adding a more useful error instead of `Cannot read property 'id' of null`. 

Any other option would probably be a significant refactor project, though.  For instance, I'm kind of liking the idea of the listener and handler being decoupled with some kind of job queue, along with some kind of lock placed on a listing ID to enforce idempotent processing of events while still allowing some level of concurrency.  Would give the opportunity to restart jobs that fail due to a bug as well instead of re-running the listener for backfill.  However, that's completely non-trivial, perhaps not a priority right now, and might not be taking something into consideration that I'm not aware of.

Could just re-institute trailing blocks again... but that wouldn't necessarily eliminate this issue either. Trail blocks(or confirmations) is just a fixed delay as opposed to an increasing backoff that my PR uses.

Maybe this PR is a temporary fix and we can consider something else for long term handling of dealing with this kind of issue in the listener/handlers.

Maybe running our own geth instances for each listener and each network is an option.  At least then we can be relatively sure that everything from event fetching through contract data calls will be from the same state.  But running geth nodes is super expensive and adds one more piece of infra that needs to be managed...  Maybe Alchemy is a little better, but I don't think we can depend on them to *never* have chain sync issues.

Whether now or later, the listener/handlers taken as a whole need to be able to cope with this issue and verify any data it gets from the JSON-RPC provider.

**Comment by mikeshultz** [comment]
Killing that PR.  This appears to be cause by the graphql cache again, which has been disabled since this error was originally seen.  That's why the `No such listing...` log message from eventsource is only seen once.  With the cache disabled, the standard `withRetries` call in the handler should cope with this issue as long as the JSON-RPC backend is relatively healthy.

Testing with purposely bad graphql queries with an up to date master branch shows behavior we should expect.  This issue can probably be closed.
