### ISSUE TITLE
Show listing creation time on listing detail component

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin#23]
We need to show when a listing was made. 

The `create()` method of our contract should add the timestamp from the `now` global. 
http://solidity.readthedocs.io/en/develop/units-and-global-variables.html#block-and-transaction-properties

The `listingStruct` would need a `createTimestamp` property too. 

And then this needs to be shown in the app when the listing is displayed.

**Comment by bretfunk** [comment]
Does this placement work for the timestamp?  And what format would you like it in, just ```Feb 02, 2018```?

<img width="709" alt="screen shot 2018-02-02 at 11 52 19 am" src="https://user-images.githubusercontent.com/2019012/35745066-fc8149be-080f-11e8-9da1-d5e1ba3e61ca.png">

**Comment by wanderingstan** [comment]
For date formate, lets go with default js locale formatting: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

IIRC, adding this will mean a change to the contract code, which means it won't be compatible with the contract we've currently got on Ropsten and Rinkeby testnets. 

This is good motivation for us to start thinking about our contract upgrade/versioning strategy!

At minimum, we'll need to make a new branch to hold this and other changes that affect the contract code.

**Comment by bretfunk** [comment]
Correct, the contract will need to be changed.  I will follow your instructions from issue #23.

Below is the updated version.  It automatically defaults to the language of the browser.  I checked all of the Origin website languages and they all work.  The JS date formatting solution is pretty gross because it is a value inside of an object so I had to make it output correctly using only one line.  Please let me know if there is a better way!

<img width="413" alt="screen shot 2018-02-02 at 1 40 24 pm" src="https://user-images.githubusercontent.com/2019012/35749163-af963c90-081e-11e8-90d7-e8dfd414b825.png">

Method: ```(new Date(Date(listing[5].toNumber()))).toLocaleDateString(`${navigator.language}`, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })```

**Comment by micahalcorn** [comment]
Changed my mind: reopening with clarification coming soon...

**Comment by micahalcorn** [comment]
Clarification never came 😬Closing this for now 🚪
