### ISSUE TITLE
Mobile Hourly Purchases

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2438]
It seems to be impossible to make an offer using Coinbase Wallet with an hourly fractional listing. I think I'm selecting a single timeslot on the calendar, but it's not populating the "Start" field. I certainly can't find a way to select a range.

**Comment by zharinov** [comment]
Just tried to reproduce by opening Coinbase Wallet dapp browser at `https://dapp.staging.originprotocol.com/#/listing/4-000-324` ("Test Hourly" listing):

<img src="https://user-images.githubusercontent.com/1239644/60348497-ba56aa80-99d0-11e9-81c3-4ad8b2fab948.png" width="350"/>

There is some weirdness of price rendering, but selection seem to be working.
For now I can't check it out with Android, but maybe will try later.

@micahalcorn, am I correct on reproduce steps or it's better to try another way?

**Comment by shahthepro** [comment]
@zharinov 

If I am not mistaken, the problem was that if you touch a single slot, the start and end date/time slots won't be filled. You had to touch a single slot twice.

I'm at present working on redesigning Listing Detail page and I pushed [a commit](https://github.com/OriginProtocol/origin/commit/89b99830b265f7c63109558540f973f5b7f87d51) that should fix the double-tab for single time/date slot selection issue.

**Comment by zharinov** [comment]
@shahthepro thank you, now I see. Cool, then I'll search for other good first task.

**Comment by franckc** [comment]
@shahthepro I'm looking at good first issues for new developers. Is this already fixed ? If not, I could assign it to a new developer. Let me know. Thanks.

**Comment by micahalcorn** [comment]
This appears to be fixed, although the UX is still terrible. 😔
