### ISSUE TITLE
Origin Marketplace authentication settings

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#2465]
The Origin Marketplace mobile app has no way to change authentication once it is configured during the onboarding. We should add these to the settings:

- Enable/disable Face/TouchID
- Change PIN

**Comment by franckc** [comment]
@angwangri Could you look at this issue ?
@micahalcorn Is going to add some UI mocks for it to Zeplin..

**Comment by micahalcorn** [comment]
Here is a starting point:

- [Settings](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5d92a607af15cb787cee6e77)
- [Pin Code](https://app.zeplin.io/project/59fa2311bac7acbc8d953da9/screen/5d92a6073689f402743a1d29)

There are several UX considerations. I will update this comment with some thoughts. 🤔

**Comment by micahalcorn** [comment]
A user who wants to change her authentication settings may have one or more authentication strategies enabled: facial recognition, fingerprint, or pin code. Most users will have exactly one of them because we require one but don't allow users to choose more than one during onboarding. The user is prompted to establish one of the biometric strategies (whichever is applicable for the device) or a PIN code as an alternative. The user should be able to disable all authentication strategies after completing onboarding if she so chooses. She may also enable any or all of them, but only the relevant biometric will be an authentication requirement if multiple options are enabled.

**Facial Recognition / Fingerprint**

- a toggle switch that enables or disables the biometric authentication feature
- prompts the user with a native alert to confirm when disabling
- after the prompt is confirmed, passing the biometric test is required prior to it actually disabling (even though it can be done from the phone's settings without this)
- operates independently of whether or not the PIN code is enabled

**PIN Code**

- a toggle switch that enables or disables the six-digit passcode
- prompts the user with a native alert to confirm when disabling
- after the prompt is confirmed, the existing code must be entered
- operates independently of whether or not the biometric is enabled
- when the toggle is switched to enabled, a screen should appear requiring the code input followed by another one with a confirmation input
- when a user wants 
- if entering a code is canceled, the back button should lead back to the settings screen and the toggle switch's state should be reversed
- when a switch is toggled, its state should change prior to the prompt appearing and its state should reverse if the prompt is declined/canceled

**Triggering Authentication**

When opening the app, if both biometric and PIN are enabled, only the biometric test should be presented to the user. There should be a button for the user to input the PIN as a fallback if the biometric isn't working.

Let's convert this "Retry" button to one with a blue outline and no fill. Then add a similar button below that says "Use Pin Code" _if_ it is enabled.

![auth-fail](https://user-images.githubusercontent.com/273937/66017944-dbc4a800-e491-11e9-876c-10144290ea9f.png)

cc @franckc @matthewliu

**Comment by micahalcorn** [comment]
Considering this done via https://github.com/OriginProtocol/origin/pull/3688 ✅
