### ISSUE TITLE
Publish Changes stays disabled

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#2484]
Change in profile verification should enable `Publish Changed` , instead is stays disabled. It gets enabled only if name/description data is changed

**Comment by sparrowDom** [comment]
@shahthepro @micahalcorn I assume you already know about this one?

**Comment by shahthepro** [comment]
Yes @sparrowDom, Seems like the "Publish" button is disabled when it should be enabled and vice versa. Probably I missed a "NOT" operator somewhere while checking for unpublished changes or possibly a bad merge.

"Publish Changes" button will no longer be there after PR #2467 gets merged. So that should close this one.

**Comment by sparrowDom** [comment]
Great, added this ticket id to the PR that will close it.
