### ISSUE TITLE
Request: Test DApp on Chrome on a PC

### ISSUE THREAD

**Issue by davecraige** [OriginProtocol/origin#328]
We would love your help testing the DApp on a PC with Chrome + Metamask extension.

Please report your findings below for the following:

- Log in to http://demo.orginprotocol.com
- Create an attestation
- Create a listing
- Purchase an item

Feel free to make PR to the [ReadMe test section](https://github.com/OriginProtocol/origin-dapp#browser--wallet-compatibility) with your results.

**Comment by vikaskyadav** [comment]
See https://github.com/OriginProtocol/origin-dapp/pull/345

**Comment by acal** [comment]
Testing Demo on Win10 with Chrome 68.0.3440.75 (Official Build) beta (64-bit). So far everything works BUT will a fair amount of lag/latency (~3-8 sec average and sometimes as much as a minute for "My Purchases" page) at page load or when updating a page or state after clicking a button. The lag is large enough that one might wonder if the server is working or if an extra button click or page reload on the GUI is needed. It is too long for happy UX.

This lag occurs on most page loads and actions. Eg. My Sales, My Purchases, Send the Product to the Buyer Button. It also has a lot of latency to load my profile avatar and details in the profile dropdown (upper right corner) area.

For the Facebook attestation I could not get that to work and got the following error message in a modal from the FB api: "App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions."

Otherwise UI looks good and everything seems to work so far!

**Comment by davecraige** [comment]
Thanks for your detailed feedback @acal. 🙏

**Comment by concerned3rdparty** [comment]
Selecting a different language from the footer dropdown has no effect, it reselects its default language , in my case it is Turkish.

**Comment by micahalcorn** [comment]
Closing this for now 😐
