### ISSUE TITLE
Cancel listing promotion

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#3409]
When a user starts listing promotion, there is no way to exit the activity. (except for hardware back button). Happening on Mobile wallets
![Screenshot_20190916-153041](https://user-images.githubusercontent.com/579910/64988508-e09f2e80-d8cb-11e9-8ac3-9a96a638b3e9.jpg)

**Comment by micahalcorn** [comment]
Oh, thanks @sparrowDom 😬 Shouldn't that continue button be disabled also?

**Comment by micahalcorn** [comment]
It looks like the back button went missing. 😕 https://zpl.io/a8JJZQE

**Comment by shahthepro** [comment]
@sparrowDom I added back the back icon.

@micahalcorn 
> Shouldn't that continue button be disabled also?

I don't know how I messed this up. But the `isMainnet` constraint was on the wrong div. 😞I'm guessing @sparrowDom was on staging that's why the button was enabled (but "Your OGN deposit acts as a commission..." text was missing above the warning).
