### ISSUE TITLE
Marketplace contract: Implement the Check-Effects-Interaction design pattern

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#3413]
Currently, the Marketplace contract does not follow the [Checks-Effects-Interactions](https://solidity.readthedocs.io/en/v0.5.11/security-considerations.html#use-the-checks-effects-interactions-pattern) pattern for its interaction with the currency and the tokenAddr tokens.

**Comment by franckc** [comment]
@shahthepro Would you have time to take a stab at implementing this ? I'll ping you offline with more details. We definitely would like to understand how big of a change this is and how risky it is before we decide to merge this in...

**Comment by franckc** [comment]
CC @nick @joshfraser

**Comment by franckc** [comment]
Also note that we should be able to verify this change by running the [Slither](https://github.com/crytic/slither) tool.

Though it looks like our codebase contains contracts with duplicate names, which triggers a [known bug in Truffle](https://github.com/trufflesuite/truffle/issues/1087), preventing Slither to work directly on our codebase. If the duplicate names are changed, the static analyzer will work.

**Comment by shahthepro** [comment]
@nick @franckc Just asking, are we also planning to bump the solidity version from 0.4 to 0.5? If not, why are we sticking with 0.4?

**Comment by franckc** [comment]
Mainnet contracts for OGN and Marketplace were compiled and deployed a while ago on Mainnet using 0.4.24.

As far as I know, the reason we did not upgrade yet is because we want to be able to compile contracts in our test environment using 0.4.24 to reproduce as closely as possible what is currently deployed to Mainnet. In the future, I'd expect we'll find a way to support compiling using different version of the solidity compiler, so that we can use more recent versions of solidity for new contracts we develop.

**Comment by nick** [comment]
The Proxy contracts are using Solidity 0.5, but are compiled by solc directly instead of truffle. I think we should try to stay away from truffle in general as they always lag behind solc and often take months to catch up. For example the Proxy contracts used features of Solidity unavailable in the solc version bundled with truffle at the time of development.

Dealing with 2 different versions of truffle in the same codebase doesn't seem doable right now, hence solv v5 contracts having an extension of .s instead of .sol.
