### ISSUE TITLE
Show map of listing location

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin#37]
Add map to listing-detail showing listing location. Probably using openstreetmaps

**Comment by wanderingstan** [comment]
(Responding to PM)

The `address` field of a listing is almost certainly going to be derived from the [`PostalAddress`](http://schema.org/PostalAddress) standard or [GeoCoordinates](http://schema.org/GeoCoordinates). 

`GeoCoordinates` looks like the simpler one to start with. 

At this early stage I don't think we're so concerned with quality of the data or whatnot. It will take us some time just to settle on the schema design and the UI design. I think swapping between OSM, Google, Bing, etc... should be straightforward. And in the end, Origin DApp creators are free to use any solution they like.

**Comment by ambertch** [comment]
Some research...

OpenStreetMap has an API, but it is for platform related calls, rather than address/map queries it seems (https://wiki.openstreetmap.org/wiki/API_v0.6).

One way to do this:

1. obtain address from user
2. look up geo coordinates (lat/long)
3. store coordinates
4. display map

With the address, this is currently a string field in the form to create a listing. Using the http://schema.org/GeoCoordinates format, a user can be asked to specify the postal code + country. Having that data will result in better resolution if OpenSteetMap is used.

With looking up coordinates, OpenStreetMap doesn't have as complete of a dataset as the other providers; doing some queries I saw that zipcodes generally resolve in OSM but sometimes specific addresses do not. Since this is an API request, I think this also needs to use either CORS or the bridge server.

With storing the coordinates, one option is to extend the listing schemas with field(s) for coordinates and write it to IPFS.

For displaying the map, both OpenStreetMap and Leaflet (which wraps OSM) take lat/long coordinates. Using a wrapper library (Leaflet) enables annotations to be easily added (such as the red pointer dot in Google Maps). Using Leaflet.js might also work better on mobile (since it can resize to fill the screen http://leafletjs.com/examples/mobile/example.html)

The map corresponding to an address lookup in OpenStreetMap can be exported as an iframe, but I don't think this can be obtained from a query. I looked at using the query as an API request of sorts (openstreetmap.org/search?query=94107), but getting the coordinates involves a redirect which is done in javascript (openstreetmap.org/search?query=94107#map=19/37.79530/-122.40939), so following HTTP redirects won't work.

**Comment by ambertch** [comment]
Here is an example of what the UI might look like, displaying the map below main listing information, above ancillary information. This example uses OpenStreetMap, so there is no annotation for the specific location (520 20th St, Oakland, CA 94612):

<img width="876" alt="screenshot 2018-04-17 19 05 10" src="https://user-images.githubusercontent.com/156263/38909318-037b4e88-4279-11e8-9599-20a2dbc0355c.png">

**Comment by ambertch** [comment]
If using the Google Maps API, geocoding + map display can be done in-browser https://developers.google.com/maps/documentation/javascript/geocoding

**Comment by ambertch** [comment]
With Geocoding using OpenStreetMap, the site actually runs on a service called Nominatim (https://nominatim.openstreetmap.org/), which is open source (https://github.com/openstreetmap/Nominatim)

I tried issuing a POST request to nominatim.openstreetmap.org/search.php to see if geocoding could be done programmatically, but the service returns HTML with a list of results. Since the server itself is PHP on top of PostGIS/Postgres, an option there would be to set up an instance and implement an API.

**Comment by jordajm** [comment]
@ambertch nice research on this one - thanks! Cool if I run with it from here for a bit or would you like to take it on?

**Comment by micahalcorn** [comment]
@wanderingstan we're currently not even showing the plan-text `location` value anywhere in the DApp, are we?

**Comment by lucadgtrip** [comment]
we were contacted by https://what3words.com/ as we are presenting at the same conference in London in November.
I just talked to them.
They usually charge companies for access to APIs and KPIs but would be happy to give us (meaning Origin) free access.
It's a for profit company so we can't be sure they won't change their model or disappear (they exist since 2013 though) but if used alongside other integrations it could be a nice to have.
You may want to check it out.

**Comment by lucadgtrip** [comment]
![Screenshot 2019-08-16 at 12 35 11](https://user-images.githubusercontent.com/34341206/63158615-504aa100-c022-11e9-8ca8-990b159d5b25.png)

first in App Store. They may becoming a thing. Let's keep an eye on them.

**Comment by micahalcorn** [comment]
Fascinating 🤔 Thx Luca!

**Comment by lucadgtrip** [comment]
a less flattering take of the What3Words solution:
https://news.ycombinator.com/item?id=21184505

**Comment by micahalcorn** [comment]
Resolved (for Housing listings) by https://github.com/OriginProtocol/origin/pull/3797 🗺
