### ISSUE TITLE
Self referrals should not be allowed

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#4250]
In the prod database, I'm seeing ~300 entries in the growth_referral table where referrer and referee are identical.

This query shows the accounts:
select * from growth_referral where referrer_eth_address = referee_eth_address;

I'm not sure how this could happen since the only place we write to growth_referral is in the method makeReferralConnection and it does have [a check](https://github.com/OriginProtocol/origin/blob/master/infra/growth/src/resources/invite.js#L81) to prevent exactly this from happening!

**Comment by franckc** [comment]
@sparrowDom I have been staring at this code for 10 minutes and I don't see how this could be happening... any idea? :)

**Comment by sparrowDom** [comment]
This is a weird one. After debugging I've found 2 issues with referral codes: 
- we store the referral code in [navigations package](https://github.com/OriginProtocol/origin/blob/288423f3d582fd0746096988799bbe4c13114f17/infra/notifications/src/app.js#L282) and there are no checks there. This must be the reason for the bug
- after debugging in local docker environment, the whole `enrol` endpoint in growth  server is never called. Since the authentication server does the signing-in part. And from my testing the referral link on desktop is never made. 

Preparing a fix for these 2 issues

**Comment by franckc** [comment]
oh... yes I totally missed that referrals are also inserted from the notification server. that must be it.
excellent catch sir!

**Comment by sparrowDom** [comment]
Fix here: https://github.com/OriginProtocol/origin/pull/4277

**Comment by sparrowDom** [comment]
fixed via https://github.com/OriginProtocol/origin/pull/4277
