### ISSUE TITLE
Listing Types Not Localized

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#678]
This probably isn't blocking, but should likely be prioritized over other localization quirks. Did I break this?

<img width="1440" alt="screen shot 2018-10-03 at 4 51 15 pm" src="https://user-images.githubusercontent.com/273937/46445694-1388fa80-c72d-11e8-8224-18ec5bb58666.png">

**Comment by micahalcorn** [comment]
Secondarily, [this injection of the translated type](https://github.com/OriginProtocol/origin-dapp/blob/master/src/components/listing-create.js#L352) should be replaced with multiple formatted messages; one for each listing type.

**Comment by jordajm** [comment]
@micahalcorn I think it's possible that @sparrowDom fixed this issue [here](https://github.com/OriginProtocol/origin/pull/396), but the listing type names still show up in English because Crowdin auto-translation hasn't been run since that PR was merged. I see errors in the browser console that would indicate this.

**Comment by micahalcorn** [comment]
Cool 🤞 We can close and reopen if necessary.
