### ISSUE TITLE
Have separate read vs write web3 provider

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#682]
During testing on Mainnet, we saw an issue where the latest listing that had been created did not show up on the Browse page and their associated listing details page also failed loading.

The issue went away after using the "Reset account" Metamask option and is very likely caused by Metamask caching.

We should strongly consider using 2 separate providers:
 - Use our own web3 provider that talks to Infura directly for all Read operations
 - Use Metamask injected web3 provider only for Write operations

The DApp could pass both a web3Read and a web3Write to the origin-js constructor.

Having a separate execution provider will also be good to call the new provider.enable() that will be enforced by MetaMask **starting Nov 2nd**

**Comment by franckc** [comment]
CC @nick @DanielVF @micahalcorn

**Comment by micahalcorn** [comment]
@franckc this should be done at the [-js](https://github.com/OriginProtocol/origin-js/) level though, right?

**Comment by franckc** [comment]
Yes, most of the work is in origin-j. There would only be a small bit to change in DApp to properly call the origin-js constructor with both a read and write web3. I filed this bug in DApp because it manifests in the DApp. Feel free to file under origin-js if it is easier for tracking.

**Comment by micahalcorn** [comment]
No big deal, just confirming 👍

**Comment by DanielVF** [comment]
Sounds like a good idea, as long as we fallback in a way that not everyone using origin.js has to give two providers.

**Comment by cuongdo** [comment]
I'll take a look at this.

**Comment by franckc** [comment]
@cuongdo reminds me of when you added support for read-only replica back in the days at the tube... :)

**Comment by cuongdo** [comment]
@franckc “History doesn't repeat itself but it often rhymes.” 😄

**Comment by cuongdo** [comment]
I've taken a look at this, and there's no reasonably clean way to do this. I created a [proof of concept](https://gist.github.com/cuongdo/b5388cb4adea4be78d852bd5d8ad5c8a) that added another `web3` instance to `contractService` just for reads. The problem is that we don't funnel all contract calls through `contractService.call()`, which makes this a somewhat invasive change. I'm postponing my efforts on this to focus on other things.

**Comment by cuongdo** [comment]
I previously created a partial PoC for the following solution:

**Reads:**
- By default, have all `Contract` objects point use a new provider that reads directly from Infura. This provider cannot sign transactions (unless we add direct support wallet too).
  - This addresses the reads that the resources sometimes issue directly to Contract objects. ([example](https://github.com/OriginProtocol/origin/blob/master/origin-js/src/contractInterface/users/v00_adapter.js#L48))
- Direct Infura reads bypass MetaMask. This means we bypass their block cache, which makes fresher reads more likely. The downside is that we might overload their servers if we don't use a cache. We can mitigate this longer term by running our own nodes.

**Writes:**
- Origin.js funnels contract writes through [contractService.call()](https://github.com/OriginProtocol/origin/blob/master/origin-js/src/services/contract-service.js#L251), which can [use the ABI](https://github.com/OriginProtocol/origin/blob/master/origin-js/src/services/contract-service.js#L270) to determine if the call mutates contract state.

Because Contract objects don't allow changing providers once constructed, `contractService` will need two arrays of contracts:
   1. (current) Array of contracts using the web3 provider given by the DApp (usually MetaMask)
   2. (new) Array of contracts using a web3 provider that reads directly from Infura (skipping MetaMask)

@tyleryasaka @franckc @nick Please let me know if I'm missing something, such as an easier way of doing this.

**Comment by franckc** [comment]
Thanks for adding all these details, super useful to capture in this issue.

Regarding handling writes using the provider from the DApp, I wonder if this approach would be ok: construct a contract object using the read provider, then determine if the specific call to the contract is a read or a write, and then
- if it is a read use the already constructed contract object to issue the call
- if it is a write, construct a new contract object using the write provider and issue the call.

Anyway, we can flesh out those details when/if we decide to implement...

**Comment by micahalcorn** [comment]
Since we have moved forward with performance mode, I'm going to close this for now. 🙂
