### ISSUE TITLE
Problems with staging deployment 10/25/2018

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin#827]
When testing I have encountered a couple of problems on staging: 
1. Deploying a new profile (contract service deploys a contract) triggers Metamask popup after 1-2 minutes. (seems IPFS related. The popup only happens after the request to IPFS timeouts)
2. Twitter and Aribnb attestations return 500 error in the second phase of confirming attestation. (this could be related to IPFS. Are `IPFS_DOMAIN` and `IPFS_PORT` correctly set in `origin-bridge.env` file?)

**IPFS pending request (full url can almost be observed in the bubble)**
<img width="1920" alt="screenshot 2018-10-25 12 40 21" src="https://user-images.githubusercontent.com/579910/47495505-a14f9580-d854-11e8-9912-f075dfc2bcb1.png">

**Popup triggered once the IPFS fetch fails**
<img width="1920" alt="screenshot 2018-10-25 12 41 59" src="https://user-images.githubusercontent.com/579910/47495561-bb897380-d854-11e8-9102-2cf65ce957aa.png">

**Airbnb attestation error**
<img width="1920" alt="screenshot 2018-10-25 12 44 10" src="https://user-images.githubusercontent.com/579910/47495627-e2e04080-d854-11e8-8efc-e6b1a45ef23f.png">

**Comment by sparrowDom** [comment]
@franckc (just to trigger notification to you inbox 😈 )

**Comment by franckc** [comment]
Here are the logs for bridge on staging: https://gist.github.com/franckc/b166416e179976cdccb7b35944d3a204

It does look like a failure to connect to IPFS which would happen if the IPFS_DOMAIN or IPFS_PORT would not be set correctly.

Let me check ENVKEY settings for bridge...

**Comment by franckc** [comment]
Checked ENVKEY setup. For staging:
IPFS_DOMAIN=ipfs.staging.originprotocol.com
IPFS_PORT=80

Now for some reason in the bridge container for staging, ENVKEY key is the production one... This needs to be fix, though there is likely another issue since the staging bridge server should not fail connecting to prod IPFS.

**Comment by franckc** [comment]
CC @tomlinton in case he has ideas...

**Comment by franckc** [comment]
I think I figured why the bridge staging deployment uses prod ENVKEY key. It turns out I ran deploy.sh from a repo I had used before where there was an existing (but old) values/secrets-staging.yaml which was still pointing to the prod ENVKEY (I had fixed as part of PR #764).

@tomlinton To prevent this from happening in future, I wonder if deploy.sh should delete values/secrests-[dev|staging|prod].yaml everytime

Let me redeploy. I think we'll still have the connectivity issue though where bridge fails to connect to IPFS - that's a separate issue I believe...

**Comment by franckc** [comment]
Thanks @tomlinton 

Bridge staging deployment now has the correct ENVKEY key (separate note: I noticed the dev bridge ENVKEY is not set to proper value in secrets - I will submit a PR for that).

I spawned a python interpreter in the bridge container and tried to make the add_json call that is used by attestation code. I got a 500 back from the ipfs server:
```
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://ipfs.staging.originprotocol.com/api/v0/add?stream-channels=true
```

Here are the logs of what I did:
https://gist.github.com/franckc/fe43df63c56cb2dd1163a9e999dff5d6

**Comment by franckc** [comment]
Based on #794, I think the ?stream-channels=true param is what's causing the issue... checking ipfs python client to see if we can disable it.

**Comment by franckc** [comment]
stream-channels=true is [hardcoded](https://github.com/ipfs/py-ipfs-api/blob/3c2d8f67ec934efae3ea11286ab5ae20fef9b50b/ipfsapi/http.py#L236) in the python client

But actually re-reading bug report #794 this could be a red-herring: on the bridge we get a 500 back. In the DApp we get a 200 but X-Stream-Error headers.

@tomlinton ping me on Discord when you start your day in your shiny new co-working space and we can investigate further... :)
