### ISSUE TITLE
Require Messaging

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#840]
Prior to creating a listing or making an offer, a user should be required to enable messaging. If messaging is not enabled, a modal prompt should appear immediately prior to the MetaMask/web3 approve/reject prompt. The design and copy for the modal should be similar to the case where a user attempts to contact another user without having messaging enabled.

**Comment by gauravsavanur07** [comment]
Hey I would like to work on This issue as my first commit

**Comment by micahalcorn** [comment]
Hi @gauravsavanur07 🙏 I've added you to the GitHub organization. So once you accept that invitation, you will be able to push your own branch instead of forking. Please feel free to work on this one. Let me know what other information you need, thanks!

**Comment by micahalcorn** [comment]
@gauravsavanur07 were you able to work on this or should someone else pick it up?

**Comment by gauravsavanur07** [comment]
There r some debugging to be done in the issue I'm working on

On 13-Nov-2018 3:43 PM, "Micah Alcorn" <notifications@github.com> wrote:

@gauravsavanur07 <https://github.com/gauravsavanur07> were you able to work
on this or should someone else pick it up?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OriginProtocol/origin/issues/840#issuecomment-438312950>,
or mute the thread

**Comment by micahalcorn** [comment]
Thanks @gauravsavanur07 👍 Let me know if I can help debug. It would be great to get this done soon.

**Comment by micahalcorn** [comment]
Resolved by https://github.com/OriginProtocol/origin/pull/982 ✅
