### ISSUE TITLE
Better handling of origin-js dependencies

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin#854]
The [package.json](https://github.com/OriginProtocol/origin/blob/master/origin-js/package.json) for `origin-js` has both dependencies (production) and devDependencies. When we publish the package and someone does an `npm install origin-js` they'll end up with all the production dependencies installed, which is unnecessary because the package includes a bundle generated by webpack which no longer has any dependencies.

Other projects like Vue place all dependencies under devDependencies to avoid this. I'd like to avoid doing that because if we install all the devDependencies when building using the CI server it is a lot slower.

Here is a proposal of how we could handle this:

- Everything required for building `origin-js` lives under `dependencies`, and everything for testing/developing lives under `devDependencies`.
- When publishing origin-js, we move all the `dependencies` to `devDependencies`. I'm intending to automate the publishing of origin-js (triggered from a tag with a version number) in the same way the deployments will be automated, so this manipulation of `package.json` could be handled automatically.

That way the CI server stays fast, and people don't end up with a bunch of unnecessary packages when they install `origin-js`. It is a bit ugly though, so if anyone has any other suggestions lets hear them!

**Comment by franckc** [comment]
CC @nick @DanielVF @wanderingstan to leverage their incommensurable experience dealing with npm...

**Comment by DanielVF** [comment]
I think Vue has all its dependencies under `devDependencies` because all of those are real dev dependencies - I see test packages, build packages, compile packages. Nothing required for running.

It seems very strange to have our NPM package contain a single js script with all third party dependencies included. You are right that doing both this and having them as `dependencies` doesn't make much sense. However, I'd be more wondering about the single file with all included dependencies. Is that a normal way of using NPM? Seems to go against what I'd expect. That certainly makes sense as a release product for people to download, but with NPM I'd expect the dependencies to live in their own folders, available for sharing.

For example, even if we move web3 to `devDependencies`,  if a downstream npm project wants to use origin.js and a web3, they are going to have web3 (and all its dependencies) in their final release code twice, once with the origin bundle and once for their own code.

**Comment by wanderingstan** [comment]
> ...incommensurable experience dealing with npm...

If Stack Overflow searching and blind trial-and-error count as "experience," then yeah, sure.. ;)

Perhaps related: Earlier this week @nick and @crazybuster and I were discussing our `webpack.config.js` and thinking we could remove `babel-polyfill` ([here](https://github.com/OriginProtocol/origin/blob/master/origin-js/webpack.config.js#L8)), since that is something done deal with old browsers. And that's a non-issue for an app using origin-js as an npm module. (We would leave it for the `clientConfig` ([here](https://github.com/OriginProtocol/origin/blob/master/origin-js/webpack.config.js#L45)), which is the version of origin-js to be used outside of npm) I suspect this would also help speed things up, as webpack-ing is pretty intensive.

**Comment by nick** [comment]
Think this is redundant now
