### ISSUE TITLE
"Returned Values aren't vaild, did you run out of gas?"

### ISSUE THREAD

**Issue by lucadgtrip** [OriginProtocol/origin#871]
Trying to access My Listings
https://dapp.originprotocol.com/#/my-listings
connected to Metamask with about 16 U$ in ETH (Mainnet)
The page got stuck as per attachment.

It happened 3 times and on last refresh it worked.

Os X, Chrome.
ETH Address:
0xce73904422880604e78591fD6c758B0D5106dD50
![screenshot 2018-11-02 at 18 45 28](https://user-images.githubusercontent.com/34341206/47928863-1879cf00-ded0-11e8-9424-7313d4bbb118.jpg)

**Comment by micahalcorn** [comment]
Potentially related to [this](https://github.com/OriginProtocol/origin/issues/799) 🤞

**Comment by nick** [comment]
The fix is as follows:

```

function applyWeb3Hack(web3Instance) {
  web3Instance.eth.abi.decodeParameters = function(outputs, bytes) {
    if (bytes === '0x') bytes = '0x00'
    return web3Instance.eth.abi.__proto__.decodeParameters(outputs, bytes)
  }
  return web3Instance
}

web3 = applyWeb3Hack(new Web3(provider))
```

I think we'll keep this on hold for now as we're currently using web3.js beta 34 which does not have this issue. If we do need to add it I think the two places would be in `origin-dapp/src/services/origin.js` lines 20-31 and `origin-js/src/services/contract-service.js` line 31.

**Comment by micahalcorn** [comment]
Closing this until we see it again 😬
