### ISSUE TITLE
Links to show on list creation: see listing

### ISSUE THREAD

**Issue by lucadgtrip** [OriginProtocol/origin#880]
After creating a listing I am presented with two buttons:
- create another listing
- see all listings
but want I really usually want is to see the listing I just created.
Maybe we could add that button too.

**Comment by micahalcorn** [comment]
Thanks for the suggestion @lucadgtrip 👍 I suspect that we originally were only presenting the "see all listings" option because the newly-created listing would be at the top of the page. But now with featured listings, slower confirmation times, and potentially more competing listings as we scale, the newly-created listing is surely below the fold and likely not on the first page of results. I think my preference is to just replace the "see all" button with your suggestion. This is also because the "review" step previously looked almost identical to the listing detail page, but that's no longer the case. Any disagreement @matthewliu @wanderingstan?

**Comment by micahalcorn** [comment]
Yes, we should just assume that a transaction hash equates to a successfully-created listing and keep all of the relevant data in Redux until we replace it with indexed data. This is covered by p3 focus area "optimistic ui", which is related to @franckc's performance efforts.

**Comment by micahalcorn** [comment]
Solved by DApp:two:
