### ISSUE TITLE
Integration with Protocol Labs IPFS cluster

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#912]
The ProtocolLabs team has setup a cluster, exposed at this [URL](https://origin.infra.ipfscluster.io:9094), that we can use to pin Origin's IPFS content in order to replicate it.

The recommended way for integrating is to use the [API client](https://godoc.org/github.com/ipfs/ipfs-cluster/api/rest/client). Note that the client is written in Go so we'll either need to port it to JS (hopefully we can re-use some of the code from [js-ipfs-api](https://github.com/ipfs/js-ipfs-ap)), or alternatively build a simple Go binary that gets spawned by JS.

We also need to decide on where in our stack we add this integration. Some options:
 - [ipfs-proxy](https://github.com/OriginProtocol/origin/tree/master/ipfs-proxy)
 - [event-listener](https://github.com/OriginProtocol/origin/tree/master/origin-discovery/src/listener)
 - separate cron job

**Comment by tomlinton** [comment]
Another option I'd like to throw in there is [Google Cloud Functions](https://cloud.google.com/functions/). It might be good here because this integration isn't something that should live in our core code. We'd still have to use something like [Cloud Pub/Sub](https://cloud.google.com/pubsub/docs/overview) to trigger the function though.

**Comment by franckc** [comment]
Yes, that could be an option. Which component of our stack would you envision enqueues the messages that get processed by Google Cloud Functions ? 
 - The ipfs-proxy could do that since it already processes all content being stored in our IPFS cluster. On the other hand that would add a dependency and could make ipfs-proxy less reliable.
 - The event-listener is another option but the drawback is that it would need to parse the JSON content from listing to look for references to IPFS hashes for things like images. And also currently event-listener does not listen for identity/profile events which have IPFS data attached to it...

**Comment by tomlinton** [comment]
The event-listener seems like a better place because there is less of a performance concern. Is there plans for the event-listener to listen for identity/profile events? If so we could just do that work first. If not then ipfs-proxy is probably better.

Adding a general option for the event-listener to use Cloud Pub/Sub might be good. We could then implement a few different things as Cloud Functions, like the Discord messaging. It'd help decouple things and reduce the complexity of the event-listener. It'd be good for performance too (when that eventually becomes a concern).

Ipfs-proxy does have a bit of an advantage in that it sees everything as it happens.

**Comment by franckc** [comment]
Yes, I wanted to update the event-listener to listen to identity events since I think it will be useful anyway to store that data in the back-end (for ex. for analytics purposes). Was more like a P2 in Q4 but should not be more than couple days of work so we could definitely prioritize it.
And yes, agreed would be good to decouple event-listener so that it only listens for events and does not do the actual work but rather delegates to workers via a queue. So this IPFS integration could be the first prototype for this architecture.
There is a slight delay (in the order of 30sec) for the listener to get events but I don't think that's a dealbreaker since regardless of using ipfs-proxy or event-listener we will only be able to achieve best-effort replication consistency between our cluster and ProtocolLabs's. 

Let's go with the direction of using the event-listener.

**Comment by tomlinton** [comment]
Done #1532 and #1215.
