### ISSUE TITLE
🐃 Messaging - Fake send times to add messages to the past

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin#994]
A malicious user can make it appear that a message was sent at any point in the past.

This would be as easy as setting a message's `created ` field to a past date and could cause a bit of havoc during dispute resolution, or otherwise be helpful for scamming.

**Comment by micahalcorn** [comment]
We could sort them in the DApp by index, but we were doing this before and there was some user confusion with messages appearing in the "wrong order" (per the timestamp). There may have been an actual bug in the sort function, but I think there is also some risk of the index not being entirely dependable either due to syncing issues. I think we can rely on the index to prove that _I_ send message A before _I_ send message B, but I'm not clear on whether or not we can know for sure that _you_ send message C before _I_ send message D.

**Comment by micahalcorn** [comment]
Closing this assuming that the timestamp now gets set on the centralized server 😬
